export const FETCH_RIDES_LOADING = "FETCH_RIDES_LOADING";
export const FETCH_RIDES_SUCCESS = "FETCH_RIDES_SUCCESS";
export const FETCH_RIDES_ERROR = "FETCH_RIDES_ERROR";
export const GET_RIDE_LOADING = "GET_RIDE_LOADING";
export const GET_RIDE_SUCCESS = "GET_RIDE_SUCCESS";
export const GET_RIDE_ERROR = "GET_RIDE_ERROR";
